version: '3.8'

services:
  mcp-server:
    build: ./apps/mcp-server
    ports:
      - "8787:8787"
    environment:
      - PORT=8787
      - NODE_ENV=production
      - MARKETCHECK_API_KEY=${MARKETCHECK_API_KEY}
      - LEAD_ENC_KEY=${LEAD_ENC_KEY}
      - DASHBOARD_INGEST_URL=${DASHBOARD_INGEST_URL}
      - DASHBOARD_INGEST_TOKEN=${DASHBOARD_INGEST_TOKEN}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8787/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - autoagent-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - mcp-server
    restart: unless-stopped
    networks:
      - autoagent-network

  monitoring:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped
    networks:
      - autoagent-network

networks:
  autoagent-network:
    driver: bridge
